### ISSUE TITLE
How to use this application?

### ISSUE THREAD

**Issue by Deleora** [DeadlySurprise/ClipCursor#1]
I'm not able to figure out how to use this application to restrict mouse to a specific region. Plz explain.
How can I make it to restrict cursor to a specify region I want, not some application window.

**Comment by MorMund** [comment]
This app is only intended to lock the cursor to a game window. If you want to lock the cursor you could use the same function used by this app https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-clipcursor. Alternatively feel free to modify my code to suit your needs.
